#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/jojo/local/bin/gatling
NAME=gatling
PIDFILE=/var/run/$NAME.pid
DESC="gatling http server"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_begin_msg "Starting $DESC: $NAME"
	start-stop-daemon --start --background --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- -c /var/www -F -S -u 1000 -n && success=1
	log_end_msg $?
	;;
  stop)
	log_begin_msg "Stopping $DESC: $NAME"
	start-stop-daemon --stop --quiet --retry 5 --oknodo --pidfile $PIDFILE --name $NAME && success=1
	log_end_msg $?
	;;
  restart)
	log_begin_msg "Restarting $DESC: $NAME"
	if start-stop-daemon --stop --quiet --retry 5 --oknodo --pidfile $PIDFILE --name $NAME; then
	  start-stop-daemon --start --background --quiet --pidfile "$PIDFILE" --exec $DAEMON -- -c /var/www -F -S -u 1000 -n && success=1
	fi
	log_end_msg $?
	;;
  *)
	N=/etc/init.d/${0##*/}
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
